# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6edef4bdde6f9776c96a310a57d3e86fc564bcd20fb1c8c74b1f8e03a66506992daba315b0ceea99e926a9fb4352b161f000c4503ca8e05617a75de88b3abd6

test:
  secret_key_base: 0cd6a0aaee446b1f8c8432a1cff0d8fcdb9af7fe922aa87c0d6e8d85b18b129d1454f3aad8bf9febfe385a4e34e515e611006835561b82bd59a631cd033fbe9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
